# Generated by Django 3.0.7 on 2020-11-24 23:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=75)),
                ('file_type', models.CharField(blank=True, max_length=75)),
                ('size', models.BigIntegerField(blank=True, default=0)),
                ('images', models.FileField(blank=True, upload_to='album')),
                ('starred', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2020, 11, 24, 23, 8, 5, 898837, tzinfo=utc))),
                ('modified', models.DateTimeField(default=datetime.datetime(2020, 11, 24, 23, 8, 5, 898855, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('starred', models.BooleanField(default=False)),
                ('trash', models.BooleanField(default=False)),
                ('gid', models.IntegerField(default=0)),
                ('children', models.ManyToManyField(related_name='_folder_children_+', to='uploads.Folder')),
                ('folderfiles', models.ManyToManyField(related_name='folderfiles', to='uploads.File')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gid', models.IntegerField(default=0)),
                ('storage', models.BigIntegerField(blank=True, default=0)),
                ('capacity', models.BigIntegerField(default=15)),
                ('number', models.IntegerField(default=0)),
                ('timesincelastlogin', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(default=datetime.datetime(2020, 11, 24, 23, 8, 5, 897129, tzinfo=utc))),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('sharedfiles', models.ManyToManyField(related_name='sharedfiles', to='uploads.File')),
                ('sharedfolders', models.ManyToManyField(related_name='sharedfolders', to='uploads.Folder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner', to='uploads.Profile'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_parent', to='uploads.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='sharedwith',
            field=models.ManyToManyField(related_name='shared_with_folder', to='uploads.Profile'),
        ),
        migrations.AddField(
            model_name='folder',
            name='users',
            field=models.ManyToManyField(related_name='folder_users', to='uploads.Profile'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to='uploads.Profile'),
        ),
        migrations.AddField(
            model_name='file',
            name='sharedwith',
            field=models.ManyToManyField(related_name='shared_with', to='uploads.Profile'),
        ),
        migrations.AddField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(related_name='file_users', to='uploads.Profile'),
        ),
    ]
