# Generated by Django 3.0.7 on 2020-11-25 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20201125_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 17, 57, 14, 338564, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 17, 57, 14, 338543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='capacity',
            field=models.BigIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creationdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 17, 57, 14, 336752, tzinfo=utc)),
        ),
    ]
